#!/usr/bin/env bash

ELI_LOG_PREFIX="$(basename $0 | tr 'a-z' 'A-Z')"
source /eli/lib/log.sh

set -e

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

# Public variables
: ${ELI_IMAGE:="Eli Linux"}
: ${ELI_VOLUME_ID:="$(sed -E 's/[^a-zA-Z0-9]/_/' <<< "$ELI_IMAGE" | tr 'a-z' 'A-Z')"}
: ${ELI_PERSISTENT_PART=y}

ISO_DST="/eli/iso.iso"
ISO_DIR="/eli/isodir"
ISO_BOOT_DIR="$ISO_DIR/boot"
ISO_GRUB_DIR="$ISO_BOOT_DIR/grub"
ISO_LIVE_DIR="$ISO_DIR/LiveOS"

function setup_isodir {  
  # Create directory structure
  rm -rf "$ISO_DIR"
  mkdir -p \
    "$ISO_DIR" \
    "$ISO_BOOT_DIR" \
    "$ISO_GRUB_DIR" \
    "$ISO_LIVE_DIR"

  cp -lr /boot "$ISO_DIR"
  mv "$ISO_BOOT_DIR/rootfs.img" "$ISO_LIVE_DIR/rootfs.img"
}

function generate_grub_cfg {
  ln -f /eli/assets/grub_iso.cfg $ISO_GRUB_DIR/grub.cfg

  rm -f $ISO_GRUB_DIR/grub_live.cfg
  ELI_BOOTLOADER_CFG_DST="$ISO_GRUB_DIR/grub_live.cfg" \
  ELI_ROOTFS_DST="live:CDLABEL=$ELI_VOLUME_ID" \
    /eli/scripts/mkgrub-config 2>&1
}

function generate_iso {
  # We disable HFS plus so everything is stored in the ESP (FAT12/16/32 filesystem).
  # https://wiki.archlinux.org/title/EFI_system_partition#Format_the_partition
  grub-mkrescue -o $ISO_DST $ISO_DIR -- \
    -hfsplus off \
    -as mkisofs -iso-level 3 -rock -joliet \
    -max-iso9660-filenames -omit-period \
    -omit-version-number -relaxed-filenames -allow-lowercase \
    -volid "$ELI_VOLUME_ID"
}

( ELI_ROOTFS_DST="/boot/rootfs.img" source /eli/scripts/prepare-install )

log_info "setting up iso dir..."
setup_isodir
log_info "iso dir setted up."

generate_grub_cfg

log_info "generating iso..."
generate_iso
log_info "iso file generated."

# if [ "$ELI_PERSISTENT_PART" = "y" ]; then
#   if [ ! -b "$ISO_DST" ]; then
#     log "\"$ISO_DST\" is a not a block device, can't add a persistent partition"
#     exit 0
#   fi
  
#   log "adding a persistent partition to \"$ISO_DST\"..."
#   log "persistent partition added to \"$ISO_DST\"."
# fi