#!/usr/bin/env bash

ELI_LOG_PREFIX="$(basename $0 | tr 'a-z' 'A-Z')"
source /eli/lib/log.sh

set -e

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

envfile="$2/etc/environment.d/99-eli.conf"
if [ ! -d "$2/etc/environment.d" ]; then
  envfile="$2/etc/environment"
fi

echo "$*" >> "$envfile"
