#!/usr/bin/env bash

SCRIPT_DIR=$(dirname $(readlink -f "${BASH_SOURCE[0]}"))

set -euo pipefail
shopt -s inherit_errexit

source "$SCRIPT_DIR/lib/log.sh"
source "$SCRIPT_DIR/lib/traps.sh"
source "$SCRIPT_DIR/lib/install_utils.sh"
source "$SCRIPT_DIR/lib/options_parser.sh"

trap exit_trap EXIT

: ${ELI_CMD_TRACE:=""}

if [ -n "$ELI_CMD_TRACE" ]; then
  set -x
fi

function eli_cmd {
  source "$SCRIPT_DIR/cmd/eli.sh"
  main $@
}

cmdname=$0

eli_cmd $@
