#!/usr/bin/env bash

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

# Store in an array as the image may contain multiple kernel version
kvers=($(ls -m /usr/lib/modules | tr -d ','))

if [ -n "$ELI_DEBUG" ]; then
  kvers_count="${#kvers[@]}"

  # Log available kernel versions on stderr
  echo "$kvers_count version(s) available(s):" >&2
  for kver in ${kvers[@]}; do
    echo "  $kver" >&2
  done
  echo "selecting ${kvers[$kver_count]}" >&2
fi

# We only return the last element in the array
# which should be the most recent version
echo "${kvers[-1]}"
