#!/usr/bin/env bash

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

: ${GRUB_CFG_DST:="/boot/grub/grub.cfg"}

if [ -e $GRUB_CFG_DST ]; then
  echo "WARNING: \"$GRUB_CFG_DST\" already exist, skipping generation"
  exit 0
fi

GRUB_DEVICE=${GRUB_DEVICE:-/} \
GRUB_DEVICE_BOOT=${GRUB_DEVICE_BOOT:-/boot} \
  grub-mkconfig -o $GRUB_CFG_DST >&2
