#!/usr/bin/env bash

set -e

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

function log {
  echo $@ >&2
}

# Public variables
: ${ELI_IMAGE:="Eli Linux"}
: ${ELI_VOLUME_ID:="$(sed -E 's/[^a-zA-Z0-9]/_/' <<< "$ELI_IMAGE" | tr 'a-z' 'A-Z')"}

ISO_DST="/eli/iso.iso"
ISO_DIR="/eli/isodir"
ISO_BOOT_DIR="$ISO_DIR/boot"
ISO_GRUB_DIR="$ISO_BOOT_DIR/grub"
ISO_LIVE_DIR="$ISO_DIR/LiveOS"

function setup_isodir {  
  # Create directory structure
  rm -rf "$ISO_DIR"
  mkdir -p \
    "$ISO_DIR" \
    "$ISO_BOOT_DIR" \
    "$ISO_GRUB_DIR" \
    "$ISO_LIVE_DIR"

  cp -lr /boot "$ISO_DIR"
  mv "$ISO_BOOT_DIR/rootfs.sqsh" "$ISO_LIVE_DIR/rootfs.img"
}

function generate_grub_cfg {
  ln -f /eli/scripts/mkiso.d/grub.cfg $ISO_GRUB_DIR/grub.cfg

  rm -f $ISO_GRUB_DIR/grub_live.cfg
  GRUB_CFG_DST="$ISO_GRUB_DIR/grub_live.cfg" \
  GRUB_DEVICE="live:CDLABEL=$ELI_VOLUME_ID" \
    /eli/scripts/mkgrub-config 2>&1
}

function generate_iso {
  # We disable HFS plus so everything is stored in the ESP (FAT12/16/32 filesystem).
  # https://wiki.archlinux.org/title/EFI_system_partition#Format_the_partition
  grub-mkrescue -o $ISO_DST $ISO_DIR -- \
    -hfsplus off \
    -as mkisofs -iso-level 3 -rock -joliet \
    -max-iso9660-filenames -omit-period \
    -omit-version-number -relaxed-filenames -allow-lowercase \
    -volid "$ELI_VOLUME_ID"
}

log "setting up iso dir..."
setup_isodir >&2
log "iso dir setted up."

log "generating grub config..."
generate_grub_cfg >&2
log "grub config generated."

log "generating iso at \"$ISO_DST\"..."
generate_iso >&2
log "iso file generated at \"$ISO_DST\"."
