#!/usr/bin/env bash

opt=()

if [ -n "$ELI_TRACE" ]; then
  set -x
  opt+="-info"
fi

SQUASHFS_DST="/eli/rootfs.sqsh"

if [ -e $SQUASHFS_DST ]; then
  exit 0
fi

mksquashfs / $SQUASHFS_DST \
  ${opt[@]} -no-progress -noappend -reproducible -e dev proc sys run boot eli