#!/usr/bin/env bash

parent_dir="$(dirname $(readlink -e $0))"

source "$ELI_PATH/lib/log"
source "$ELI_PATH/lib/traps"

set -e
trap exit_trap EXIT

function print_help {
  cat <<EOF
Install the given image onto the system

USAGE:
  eli [global options] install image_name1 image_name2 [options]

OPTIONS:
  -f, --force                apply --force flag on lvm and other command (default: false)
  -g, --grub                 path to the grub config, if empty no entry is added to
                             the config skipped (default: /boot/grub/grub.cfg)
  -h, --help                 print this menu
  -i, --initramfs-dest       destination of the initramfs, if empty the creation
                             of the initramfs is skipped (default: /boot)
  -l, --resize-lvm           prevent root lvm logical volume resize (default: false)
  -s, --squashfs-dest        destination of the root squashfs filesystem, if empty
                             the creation of the squashfs is skipped (default: '')
EOF
}

function clean_install {
  exit_code="$?"
  log="log_info"
  if [ "$exit_code" != "0" ]; then
    log="log_error"

    log_error "exit code $exit_code trapped, cleaning install..."
  fi

  # Clean container if it exist
  if [ "buildah inspect $1" != "0" ];  then
    log_info "unmounting container $ctr..."
    buildah umount "$1"
    log_info "container $ctr unmounted"

    log_info "removing container $ctr..."
    buildah rm "$1"
    log_info "container $ctr removed"
  fi

  "$log" "install cleaned, exiting with status code of $exit_code"
  return $exit_code
}

function is_lvm_lv {
  # If not block file
  if [ ! -b "$1" ]; then
    echo "false"
    return 0
  fi
  
  block="$(realpath $1)"
  lvs="$(lvdisplay -c | egrep -o '/.*' | cut -s -d ':' -f 1)"

  for lv in $lvs; do
    if [ "$(realpath $lv)" = "$block" ]; then
      echo "true"
      return 0
    fi
  done

  echo "false"
}

function install {
  local image_name="$1"
  local initramfs_dest="$2"
  local squashfs_dest="$3"
  local real_rootfs_dest="$(realpath $3)"
  local grub_path="$4"
  local resize_lvm="$5"
  local force="$6"

  log_info "starting install of $image_name image"

  from_opts=""
  if [ "$squashfs_dest" != "" ] && [ -b "$squashfs_dest" ];then
    from_opts="--device $real_rootfs_dest:$real_rootfs_dest:rw"
  fi

  log_info "creating container for install..."
  local ctr=$(buildah from $from_opts "$image_name")
  log_info "container $ctr created"

  # Clean container on error
  trap "clean_install $ctr" EXIT

  log_info "mounting container fs..."
  local ctr_rootfs=$(buildah mount "$ctr")
  log_info "container fs mounted"

  # Getting kernel version
  kver="$(uname -r || true)"
  if [ "$kver" = "" ]; then
    kver="UNDETERMINED"
  fi

  # Install initramfs
  if [ "$initramfs_dest" != "" ]; then
    log_info "generating initramfs at $initramfs_dest..."    

    mkdir -p "$ctr_rootfs/boot"
    buildah run \
      --volume $initramfs_dest:/boot \
      --volume /lib/modules:/lib/modules:ro \
      --mount=type=bind,bind-propagation=rslave,src=/dev,dst=/dev \
      --mount=type=bind,bind-propagation=rslave,src=/proc,dst=/proc \
      --mount=type=bind,bind-propagation=rslave,src=/sys,dst=/sys \
      "$ctr" "/bin/sh" "-c" "KVER=$kver IMAGE_NAME=$image_name /eli/mkinitramfs" > >(log_pipe "[BUILDAH] [INITRAMFS] %s") 2>&1
    log_info "initramfs generated at $initramfs_dest"
  else
    log_info "skipping initramfs generation"
  fi

  # Create squashfs
  if [ "$squashfs_dest" != "" ]; then
    if [ "$resize_lvm" = "true" ] && [ "$(is_lvm_lv $squashfs_dest)" = "true" ]; then
      log_info "expanding rootfs logical volume..."
      lvresize --quiet --yes $([ "$force" = "true" ] && echo "-f") \
        --extents +100%FREE $squashfs_dest || true
      log_info "rootfs logical volume expanded"
    fi

    log_info "installing root filesystem on $squashfs_dest..."
    buildah run \
      "$ctr" "/bin/sh" "-c" "echo mksquashfs / $real_rootfs_dest -noappend -e /proc /sys /run /dev" > >(log_pipe "[BUILDAH] [SQUASHFS] %s") 2>&1
    log_info "root filesystem installed"

    if [ "$resize_lvm" = "true" ] && [ "$(is_lvm_lv $squashfs_dest)" = "true" ]; then
      log_info "shrinking rootfs logical volume..."
      tmpdir="$(mktemp -d)"

      mount "$squashfs_dest" "$tmpdir"
      local size="$(df -h | tail -n +2 | tr -s ' ' | grep "$squashfs_dest" | cut -d ' ' -f 3)"
      umount -l "$tmpdir" ; rm -rf "$tmpdir"

      lvresize --quiet --yes $([ "$force" = "true" ] && echo "-f") \
        --size $size $squashfs_dest || true
      log_info "rootfs logical volume shrinked"
    fi
  else
    log_info "skipping root filesystem installation"
  fi
}

function main {
  if [ $# -eq 0 ]; then
    log_error "no image or option specified"
    print_help
    stacktrace="false"
    exit 1
  fi


  declare -A images

  # Parse images
  while [ $# -gt 0 ]; do
    case "$1" in
      -*|--*)
        break
        ;;
      
      *)
        images["$1"]=""
        shift
        ;;
    esac
  done

  local squashfs_dest=""
  local initramfs_dest="/boot"
  local grub_path="/boot/grub/grub.cfg"
  local resize_lvm="true"
  local force="false"

  # Parse options
  while [ $# -gt 0 ]; do
    case "$1" in
      -f|--force)
        shift
        force="true"
        ;;

      -g|--grub)
        shift
        grub_path=$1
        if [ $# -eq 0 ]; then
          log_error "missing --grub option value"
          stacktrace="false"
          exit 1
        fi
        shift
        ;;

      -h|--help)
        print_help
        exit 0
        ;;

      -i|--initramfs-dest)
        shift
        initramfs_dest="$1"
        if [ $# -eq 0 ]; then
          log_error "missing --initramfs-dest option value"
          stacktrace="false"
          exit 1
        fi
        shift
        ;;

      -l|--resize-lvm)
        shift
        resize_lvm="false"
        ;;

      -s|--squashfs-dest)
        shift
        squashfs_dest="$1"
        if [ $# -eq 0 ]; then
          log_error "missing --squashfs-dest option value"
          stacktrace="false"
          exit 1
        fi

        shift
        ;;

      *)
        log_error "unknown option \"$1\""
        stacktrace="false"
        exit 1
        ;;
    esac
  done

  # Ensure rootfs block device/file exist
  # if [ "$squashfs_dest" != "" ] && ([ ! -b  "$squashfs_dest" ] && [ ! -f  "$squashfs_dest" ]); then
  #   log_error "$squashfs_dest: no such block device"
  #   stacktrace="false"
  #   exit 1
  # fi

  # Ask for root permissions if not root
  if [ "$EUID" != "0" ]; then
    log_error "install require root permissions"
    stacktrace="false"
    exit 1
  fi

  for image in ${!images[@]}; do
    install "$image" "$initramfs_dest" "$squashfs_dest" "$grub_path" "$resize_lvm" "$force"
  done
}

main "$@"