#!/usr/bin/env bash

set -euo pipefail
shopt -s inherit_errexit

# $1 define the size of /tmp tmpfs.
# $1 may have a k, m or g suffix for Ki, Mi, Gi.
# $1 may also have a % suffix to limit this instance
# to a percentage of physical RAM.
echo "tmpfs	/tmp	tmpfs	mode=1777,strictatime,nosuid,nodev,size=$1,nr_inodes=1m	0	0" >> /etc/fstab