#!/usr/bin/env bash

ELI_LOG_PREFIX="$(basename $0 | tr 'a-z' 'A-Z')"
source /eli/lib/log.sh

set -e

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

if [ "$ELI_INSTALL_TYPE" = "iso" ]; then
  log_info "skipping micro code installation (ISO type installation)."
  exit 0
fi

# Microcode
if [ "$ELI_INTEL_UCODE" != "y" ]; then \
  log_info "removing intel micro code..."
  pacman -Rsn intel-ucode; \
  log_info "intel micro code successfully removed."
fi
if [ "$ELI_AMD_UCODE" != "y" ]; then \
  log_info "removing amd micro code..."
  pacman -Rsn amd-ucode; \
  log_info "amd micro code successfully removed."
fi
