#!/usr/bin/env bash

source "$ELI_PATH/lib/log"

function exit_trap {
  exit_code="$?"
  stacktrace=${stacktrace:="true"}

  if [ "$exit_code" != "0" ] && [ "$stacktrace" = "true" ]; then
    log_error "exit code $exit_code trapped, stacktrace:"
    stacktrace
  fi

  local log="log_info"
  if [ "$exit_code" != "0" ]; then
    log="log_error"
  fi

  "$log" "exit with status code of $exit_code"
  exit $exit_code
}