#!/usr/bin/env bash

parent_dir="$(dirname $(readlink -e $0))"
export ELI_PATH="$parent_dir/.."

source "$ELI_PATH/lib/log"
source "$ELI_PATH/lib/traps"

set -e
trap exit_trap EXIT

function print_help {
  cat <<EOF
eli - Linux distribution management made easy

USAGE:
  eli [global options] cmd [cmd options]
  
COMMANDS:
  build                build OCI images using efifiles or Dockerfiles
  install              install an images in the given boot partition

GLOBAL OPTIONS:
  -h, --help           print this menu
EOF
}

function main {
  if [ $# -eq 0 ]; then
    log_error "no command specified"
    print_help
    exit 1
  fi

  # Parse flags
  while [ $# -gt 0 ]; do
    case "$1" in
      -h|--help)
        print_help
        exit 0
        ;;

      *)
        break
        ;;
    esac
  done

  # We don't need trap anymore
  trap "" EXIT

  # Parse command
  while [ $# -gt 0 ]; do
    case "$1" in
      build)
        shift
        "$parent_dir/build/main" "$@"
        exit $?
        ;;

      install)
        shift
        "$parent_dir/install/main" "$@"
        exit $?
        ;;
      *)
        log_error "unknown command \"$1\""
        print_help
        exit 1
        ;;
    esac
  done
}

main "$@"