#!/usr/bin/env bash

ELI_LOG_PREFIX="$(basename $0 | tr 'a-z' 'A-Z')"
source /eli/lib/log.sh

set -e

opt=()

if [ -n "$ELI_TRACE" ]; then
  set -x
  opt+="-info"
fi

: ${ELI_ROOTFS_DST:="/boot/rootfs.img"}
: ${ELI_ROOTFS_OVERWRITE:="f"}

if [ -e "$ELI_ROOTFS_DST"  -a "$ELI_ROOTFS_OVERWRITE" != "y"  ]; then
  log_warn "rootfs image already exist, skipping generation."
  exit 0
fi

log_info "generating rootfs image..."

mksquashfs / $ELI_ROOTFS_DST \
  ${opt[@]} -no-progress -noappend -reproducible \
  -wildcards -e 'dev/*' 'proc/*' 'sys/*' 'run/*' 'boot/*' 'eli' >&2

log_info "rootfs image generated."
