#!/usr/bin/env bash

ELI_LOG_PREFIX="$(basename $0 | tr 'a-z' 'A-Z')"
source /eli/lib/log.sh

set -e

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

log_info "preparing installation..."
( source /eli/scripts/mkrootfs )
( source /eli/scripts/mkinitramfs )
log_info "ready for installation."
