#!/usr/bin/env bash

ELI_LOG_PREFIX="$(basename $0 | tr 'a-z' 'A-Z')"
source /eli/lib/log.sh

set -e

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

: ${ELI_PRE_INSTALL_HOOKS:="/eli/hooks/pre-install"}


for f in $ELI_PRE_INSTALL_HOOKS/*; do
  fname=$(basename "$f")

  if [ -x "$f" ]; then
    log_debug "executing \"$fname\" pre-install hook..."
    $f
    log_debug "\"$fname\" pre-install hook executed."
  else
    log_warn "\"$fname\" pre-install hook is not executable, skipping it."
  fi
done