#!/usr/bin/env bash

ELI_LOG_PREFIX="$(basename $0 | tr 'a-z' 'A-Z')"
source /eli/lib/log.sh

set -e

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

: ${ELI_HOSTNAME:="$ELI_DISTRIB"}

if [ -n "$ELI_HOSTNAME" ]; then
  log_info "setting up hostname..."
  echo "$ELI_HOSTNAME" > /etc/hostname
  echo "127.0.1.1    $ELI_HOSTNAME.localdomain	  $ELI_HOSTNAME" >> /etc/hosts
  log_info "hostname successfully setted up."
else
  log_warn "no hostname specified, skipping hostname setup."
fi
