#!/usr/bin/env bash

ELI_LOG_PREFIX="$(basename $0 | tr 'a-z' 'A-Z')"
source /eli/lib/log.sh

set -e

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

: ${ELI_KEYMAP:="en"}

log_info "setting keymap to \"$ELI_KEYMAP\"..."
echo "KEYMAP=$ELI_KEYMAP" > /etc/vconsole.conf
log_info "keymap successfully setted up."
