#!/usr/bin/env bash

ELI_LOG_PREFIX="$(basename $0 | tr 'a-z' 'A-Z')"
source /eli/lib/log.sh

set -e

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

: ${ELI_LOCALE:="en_US.UTF-8 UTF-8"}

log_info "setting up locale to  \"$ELI_LOCALE\"..."
sed -i -E "s/#$ELI_LOCALE/$ELI_LOCALE/" /etc/locale.gen
locale > /etc/locale.conf
log_info "locale successfully setted up."
