#!/usr/bin/env bash

ELI_LOG_PREFIX="$(basename $0 | tr 'a-z' 'A-Z')"
source /eli/lib/log.sh

set -e

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

: ${ELI_TZ:-"Etc/UTC"}

log_info "changing timezone to \"$ELI_TZ\"..."
ln -sf "/usr/share/zoneinfo/$ELI_TZ" /etc/localtime
log_info "timezone successfully changed."