FROM docker.io/library/archlinux:latest

ARG ELI_DISTRIB=archlinux

# Install packages required for an install
RUN pacman -Syu --needed --noconfirm --hookdir $(mktemp -d) \
  dracut \
  squashfs-tools \
  grub \
  libisoburn \
  mtools \
  linux \
  linux-firmware \
  lvm2 \
  cryptsetup \
  efibootmgr \
  fuse-overlayfs \
  intel-ucode \
  amd-ucode \
  && pacman -Scc

RUN rm -rf /boot/grub*

COPY --chmod=755 $ELI_DISTRIB/hooks/pre-install/ucode /eli/hooks/pre-install/ucode

# include "distributions/.grub/Containerfile"
# include "distributions/.dracut/Containerfile"
# include "distributions/.common/Containerfile"

# Remove NoExtract from pacman conf
RUN sed -i -E 's|^NoExtract\s+=\s+.*$||' /etc/pacman.conf

# Link kernel to /boot/vmlinuz-*
RUN ln /usr/lib/modules/$(/eli/scripts/kver)/vmlinuz /boot/vmlinuz-$(/eli/scripts/kver)
