FROM docker.io/library/archlinux:latest

ARG ELI_DISTRIB=archlinux

# Install packages required for an install
RUN pacman -Syu --needed --noconfirm --hookdir $(mktemp -d) \
  rsync \
  dracut \
  squashfs-tools \
  grub \
  libisoburn \
  mtools \
  linux \
  linux-firmware \
  lvm2 \
  cryptsetup \
  efibootmgr \
  fuse-overlayfs \
  intel-ucode \
  amd-ucode \
  && pacman -Scc

# Clean /boot directory
RUN rm -rf /boot/grub*

# Remove root password
RUN passwd -d root

# include "distributions/.common/Containerfile"
# include "distributions/.grub/Containerfile"
# include "distributions/.dracut/Containerfile"
# include "distributions/.systemd/Containerfile"

# Remove NoExtract from pacman conf
RUN sed -i -E 's|^NoExtract\s+=\s+.*$||' /etc/pacman.conf

# Link kernel to /boot/vmlinuz-*
RUN ln /usr/lib/modules/$(/eli/bin/kver)/vmlinuz /boot/vmlinuz-$(/eli/bin/kver)

# Sets systemd as entrypoint so podman starts containers as system container
ENTRYPOINT ["/usr/lib/systemd/systemd"]
