#!/usr/bin/env bash

function _eli_args_csv_headers {
  printf "Name;Descriptions;Default value\n"
}

function eli_add_arg {
  if [ $# -lt 2 ]; then
    log_fatal $(printf "eli_add_arg required at least two arguments, got %s" $#)
  fi

  local name="$1"
  local desc="$2"
  local default="$3"

  printf "%s;%s;%s\n" "$name" "$desc" "$default"
}

function _eli_print_args {
  local csv_file="$1"
  
  log_info "Elifile args:"
  column $csv_file --output-separator=' | ' -t -s ';'
}


