#!/usr/bin/env bash

if [ -n "$ELI_TRACE" ]; then
  set -x
fi

# Public variables
: ${ELI_KVER:=$(/eli/scripts/kver)}

if [ -f "/boot/initramfs-$ELI_KVER.img" ]; then
  exit 0
fi

dracut --reproducible --force \
  $@ "/boot/initramfs-$ELI_KVER.img" "$ELI_KVER" >&2
